apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-pro.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: pymom-managerselect-dev
  name: pymom-managerselect-dev
  namespace: pymom-dev
spec:
  type: NodePort
  ports:
  - name: "6502"
    port: 6502
    targetPort: 5000
    nodePort: 6502
  selector:
    io.kompose.service: pymom-managerselect-dev
status:
  loadBalancer: {}