version: '3'
services:
  pyweiwaityv1_register_pro:
    image: java:8
    container_name: pyweiwaityv1_register_pro
    hostname: pyweiwaityv1_register_pro
    restart: always
    ports:
      - 6850:5000
    volumes:
      - /etc/localtime:/etc/localtime
      - /application/docker_hub/java/pyweiwaityv1/register_pro:/java8
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD-SHELL", "ss -tnlp|grep -w 5000|grep -v grep"]
      interval: 5s
      timeout: 2s
      retries: 3
    entrypoint:
      - java
      - -Xms128m
      - -Xmx256m
      - -jar
      - /java8/app.jar
      - --server.port=5000
      - --spring.profiles.active=pro
    networks:
      - pro

  pyweiwaityv1_register_pro:
    image: java:8
    container_name: pyweiwaityv1_register_pro
    hostname: pyweiwaityv1_register_pro
    restart: always
    ports:
      - 6850:5000
    volumes:
      - /etc/localtime:/etc/localtime
      - /application/docker_hub/java/pyweiwaityv1/register_pro:/java8
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD-SHELL", "ss -tnlp|grep -w 5000|grep -v grep"]
      interval: 5s
      timeout: 2s
      retries: 3
    entrypoint:
      - java
      - -Xms128m
      - -Xmx256m
      - -jar
      - /java8/app.jar
      - --server.port=5000
      - --spring.profiles.active=pro
    networks:
      - pro

pyweiwaityv1_pythonmodule_pro:
    #image: outsource_py:3.6.1
    image: python_pymom:3.6.1
    container_name: pyweiwaityv1_pythonmodule_pro
    hostname: pyweiwaityv1_pythonmodule_pro
    restart: always
    ports:
      - 6859:6859
    volumes:
      - /etc/localtime:/etc/localtime
      - /application/docker_hub/java/pyweiwaityv1/pythonmodule_pro:/python3
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD-SHELL", "netstat -tnlp|grep -w 6859|grep -v grep"]
      interval: 5s
      timeout: 2s
      retries: 3
    entrypoint:
      - python
      - -u
      - /python3/manage.py
      - runserver
      - 0.0.0.0:6859
    networks:
      - pro

networks:
  pro:
    external: false
